name: Docker Auth Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set tag
      id: vars
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ttimagesregistry.azurecr.io/dashservice:${{ env.TAG }}

    - name: log into my repository
      run: docker login ttimagesregistry.azurecr.io -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
      
    - name: push step
      run: docker push ttimagesregistry.azurecr.io/dashservice:${{ env.TAG }}